### PR TITLE
Support for kernel 6.7

### PR DESCRIPTION
**Pull request by terraluna977**
I have added the changes needed to build on kernel 6.7. I still do not really have a machine to test it out, as my old Macbooks are using HFS+ :-(. So please retest the runtime...

### CODE REVIEW

**Comment by eafer** [comment]
Thanks! I'll review this and pick it up before the 6.7 release.

**Comment by AntoineHus** [comment]
Hello, 
Any help on the testing ?

**Comment by eafer** [comment]
The 6.7 kernel won't be out for a few weeks, so I wasn't rushing this. Do you need it now?

**Comment by eafer** [comment]
This patch just got applied to the latest release. Thanks again.

**Pull request closed without merging**
