### PR TITLE
fix: unable to install with dkms

### PR DESCRIPTION
**Pull request by zeroday0619**
`
MAKE[0]="make KERNELDIR=/lib/modules/${kernelver}/build"
`
`
CLEAN="make clean"
`

### CODE REVIEW

**Comment by eafer** [comment]
Hi, thanks for the patch. Can you elaborate a little on what the problem is here?

I don't use dkms myself, this config file was originally provided by the Arch packager. But I think the arch and debian packages do use it and nobody mentioned any build failures. It's also not clear to me what your patch is intended to do: there is no `KERNELDIR` var to be set in my makefile and, according to the man page, `CLEAN="make clean"` is supposed to be the default.

**Comment by zeroday0619** [comment]
@eafer 
image

**Comment by eafer** [comment]
I just tried the dkms build on 5.19.0 and it seems to work. Can you share the content of the `make.log` you got after the first attempt? Maybe the kernel api has changed again.

**Comment by eafer** [comment]
It's been a few months so I'm closing this for now. Feel free to reopen if you are still having problems.

**Pull request closed without merging**
